language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: hhvm
  allow_failures:
    - php: hhvm
    - php: 7.1
    - php: 7.2

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
 
script: phpunit
