language: php

# Run on container environment (needed for trais caching feature)
sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.5
      env: DEPENDENCIES='low'
    - php: 5.6
    - php: 7.0
    - php: 7.0
      env: DEPENDENCIES='low'
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: hhvm-3.24
  allow_failures:
    - php: 5.5
    - php: 5.5
      env: DEPENDENCIES='low'
    - php: 5.6
    - php: 7.0
    - php: 7.0
      env: DEPENDENCIES='low'
    - php: hhvm-3.24
    - php: 7.4

dist: trusty

# Cache composer files for faster test times
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls
  - composer install

install:
  - if [ -z "$DEPENDENCIES" ]; then composer install --no-interaction --prefer-dist; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --no-interaction  --prefer-dist --prefer-lowest; fi;
 
script: vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls -v
